name: Lint & test

on:
  push:
    branches:
      - master
  pull_request:
    # types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'
    
jobs:
  test:
    name: Lint & test on node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ '20.x', '18.x' ]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Run test to generate coverage
        run: npm run test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2